import Head from 'next/head'

export default function Test() {
  return (
    <div>
      <Head>
        <title>Monochrome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico"></link>
      </Head>
Hello
     </div>

      );
}
